import { db } from '@/db';
import { groundwaterAssessments } from '@/db/schema';

async function main() {
    const sampleAssessments = [
        // Karnataka (Safe region - Region ID 1)
        {
            regionId: 1,
            assessmentYear: 2019,
            annualRecharge: 125.5,
            extractableResources: 112.95,
            totalExtraction: 68.0,
            stageOfExtraction: 'Safe',
            extractionRatio: 60.2,
            trend: 'Stable',
            assessmentDate: '2019-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 1,
            assessmentYear: 2020,
            annualRecharge: 130.2,
            extractableResources: 117.18,
            totalExtraction: 70.5,
            stageOfExtraction: 'Safe',
            extractionRatio: 60.1,
            trend: 'Stable',
            assessmentDate: '2020-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 1,
            assessmentYear: 2021,
            annualRecharge: 140.8,
            extractableResources: 126.72,
            totalExtraction: 75.2,
            stageOfExtraction: 'Safe',
            extractionRatio: 59.3,
            trend: 'Increasing',
            assessmentDate: '2021-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 1,
            assessmentYear: 2022,
            annualRecharge: 138.5,
            extractableResources: 124.65,
            totalExtraction: 78.8,
            stageOfExtraction: 'Safe',
            extractionRatio: 63.2,
            trend: 'Stable',
            assessmentDate: '2022-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 1,
            assessmentYear: 2023,
            annualRecharge: 145.3,
            extractableResources: 130.77,
            totalExtraction: 82.1,
            stageOfExtraction: 'Safe',
            extractionRatio: 62.8,
            trend: 'Increasing',
            assessmentDate: '2023-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Maharashtra Safe (Region ID 2)
        {
            regionId: 2,
            assessmentYear: 2019,
            annualRecharge: 95.2,
            extractableResources: 85.68,
            totalExtraction: 58.5,
            stageOfExtraction: 'Safe',
            extractionRatio: 68.3,
            trend: 'Stable',
            assessmentDate: '2019-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 2,
            assessmentYear: 2020,
            annualRecharge: 88.7,
            extractableResources: 79.83,
            totalExtraction: 55.2,
            stageOfExtraction: 'Safe',
            extractionRatio: 69.1,
            trend: 'Stable',
            assessmentDate: '2020-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 2,
            assessmentYear: 2021,
            annualRecharge: 105.4,
            extractableResources: 94.86,
            totalExtraction: 62.8,
            stageOfExtraction: 'Safe',
            extractionRatio: 66.2,
            trend: 'Increasing',
            assessmentDate: '2021-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 2,
            assessmentYear: 2022,
            annualRecharge: 98.9,
            extractableResources: 89.01,
            totalExtraction: 64.5,
            stageOfExtraction: 'Safe',
            extractionRatio: 72.5,
            trend: 'Stable',
            assessmentDate: '2022-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 2,
            assessmentYear: 2023,
            annualRecharge: 112.6,
            extractableResources: 101.34,
            totalExtraction: 68.9,
            stageOfExtraction: 'Safe',
            extractionRatio: 68.0,
            trend: 'Increasing',
            assessmentDate: '2023-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Punjab Semi-Critical (Region ID 3)
        {
            regionId: 3,
            assessmentYear: 2019,
            annualRecharge: 85.3,
            extractableResources: 76.77,
            totalExtraction: 68.2,
            stageOfExtraction: 'Semi-Critical',
            extractionRatio: 88.8,
            trend: 'Stable',
            assessmentDate: '2019-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 3,
            assessmentYear: 2020,
            annualRecharge: 78.5,
            extractableResources: 70.65,
            totalExtraction: 72.8,
            stageOfExtraction: 'Semi-Critical',
            extractionRatio: 103.0,
            trend: 'Declining',
            assessmentDate: '2020-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 3,
            assessmentYear: 2021,
            annualRecharge: 92.1,
            extractableResources: 82.89,
            totalExtraction: 75.4,
            stageOfExtraction: 'Semi-Critical',
            extractionRatio: 90.9,
            trend: 'Stable',
            assessmentDate: '2021-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 3,
            assessmentYear: 2022,
            annualRecharge: 88.7,
            extractableResources: 79.83,
            totalExtraction: 78.9,
            stageOfExtraction: 'Semi-Critical',
            extractionRatio: 98.8,
            trend: 'Declining',
            assessmentDate: '2022-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 3,
            assessmentYear: 2023,
            annualRecharge: 82.4,
            extractableResources: 74.16,
            totalExtraction: 82.5,
            stageOfExtraction: 'Semi-Critical',
            extractionRatio: 111.2,
            trend: 'Declining',
            assessmentDate: '2023-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // UP Semi-Critical (Region ID 4)
        {
            regionId: 4,
            assessmentYear: 2019,
            annualRecharge: 110.5,
            extractableResources: 99.45,
            totalExtraction: 82.7,
            stageOfExtraction: 'Semi-Critical',
            extractionRatio: 83.2,
            trend: 'Stable',
            assessmentDate: '2019-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 4,
            assessmentYear: 2020,
            annualRecharge: 105.8,
            extractableResources: 95.22,
            totalExtraction: 85.3,
            stageOfExtraction: 'Semi-Critical',
            extractionRatio: 89.6,
            trend: 'Declining',
            assessmentDate: '2020-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 4,
            assessmentYear: 2021,
            annualRecharge: 98.3,
            extractableResources: 88.47,
            totalExtraction: 88.9,
            stageOfExtraction: 'Semi-Critical',
            extractionRatio: 100.5,
            trend: 'Declining',
            assessmentDate: '2021-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 4,
            assessmentYear: 2022,
            annualRecharge: 92.7,
            extractableResources: 83.43,
            totalExtraction: 91.2,
            stageOfExtraction: 'Semi-Critical',
            extractionRatio: 109.3,
            trend: 'Declining',
            assessmentDate: '2022-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 4,
            assessmentYear: 2023,
            annualRecharge: 87.9,
            extractableResources: 79.11,
            totalExtraction: 94.8,
            stageOfExtraction: 'Semi-Critical',
            extractionRatio: 119.8,
            trend: 'Declining',
            assessmentDate: '2023-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Rajasthan Critical (Region ID 5)
        {
            regionId: 5,
            assessmentYear: 2019,
            annualRecharge: 65.2,
            extractableResources: 58.68,
            totalExtraction: 78.5,
            stageOfExtraction: 'Critical',
            extractionRatio: 133.8,
            trend: 'Declining',
            assessmentDate: '2019-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 5,
            assessmentYear: 2020,
            annualRecharge: 58.9,
            extractableResources: 53.01,
            totalExtraction: 82.3,
            stageOfExtraction: 'Critical',
            extractionRatio: 155.3,
            trend: 'Declining',
            assessmentDate: '2020-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 5,
            assessmentYear: 2021,
            annualRecharge: 72.4,
            extractableResources: 65.16,
            totalExtraction: 85.7,
            stageOfExtraction: 'Critical',
            extractionRatio: 131.5,
            trend: 'Declining',
            assessmentDate: '2021-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 5,
            assessmentYear: 2022,
            annualRecharge: 55.3,
            extractableResources: 49.77,
            totalExtraction: 89.2,
            stageOfExtraction: 'Critical',
            extractionRatio: 179.2,
            trend: 'Declining',
            assessmentDate: '2022-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 5,
            assessmentYear: 2023,
            annualRecharge: 48.7,
            extractableResources: 43.83,
            totalExtraction: 92.8,
            stageOfExtraction: 'Critical',
            extractionRatio: 211.8,
            trend: 'Declining',
            assessmentDate: '2023-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Tamil Nadu Critical (Region ID 6)
        {
            regionId: 6,
            assessmentYear: 2019,
            annualRecharge: 78.5,
            extractableResources: 70.65,
            totalExtraction: 95.2,
            stageOfExtraction: 'Critical',
            extractionRatio: 134.8,
            trend: 'Declining',
            assessmentDate: '2019-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 6,
            assessmentYear: 2020,
            annualRecharge: 68.3,
            extractableResources: 61.47,
            totalExtraction: 98.7,
            stageOfExtraction: 'Critical',
            extractionRatio: 160.5,
            trend: 'Declining',
            assessmentDate: '2020-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 6,
            assessmentYear: 2021,
            annualRecharge: 82.9,
            extractableResources: 74.61,
            totalExtraction: 102.4,
            stageOfExtraction: 'Critical',
            extractionRatio: 137.3,
            trend: 'Declining',
            assessmentDate: '2021-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 6,
            assessmentYear: 2022,
            annualRecharge: 71.2,
            extractableResources: 64.08,
            totalExtraction: 106.9,
            stageOfExtraction: 'Critical',
            extractionRatio: 166.8,
            trend: 'Declining',
            assessmentDate: '2022-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 6,
            assessmentYear: 2023,
            annualRecharge: 65.8,
            extractableResources: 59.22,
            totalExtraction: 110.3,
            stageOfExtraction: 'Critical',
            extractionRatio: 186.3,
            trend: 'Declining',
            assessmentDate: '2023-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Lucknow Over-Exploited (Region ID 7)
        {
            regionId: 7,
            assessmentYear: 2019,
            annualRecharge: 52.3,
            extractableResources: 47.07,
            totalExtraction: 125.8,
            stageOfExtraction: 'Over-Exploited',
            extractionRatio: 267.3,
            trend: 'Declining',
            assessmentDate: '2019-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 7,
            assessmentYear: 2020,
            annualRecharge: 48.7,
            extractableResources: 43.83,
            totalExtraction: 132.5,
            stageOfExtraction: 'Over-Exploited',
            extractionRatio: 302.2,
            trend: 'Declining',
            assessmentDate: '2020-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 7,
            assessmentYear: 2021,
            annualRecharge: 58.2,
            extractableResources: 52.38,
            totalExtraction: 135.9,
            stageOfExtraction: 'Over-Exploited',
            extractionRatio: 259.4,
            trend: 'Declining',
            assessmentDate: '2021-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 7,
            assessmentYear: 2022,
            annualRecharge: 43.9,
            extractableResources: 39.51,
            totalExtraction: 142.7,
            stageOfExtraction: 'Over-Exploited',
            extractionRatio: 361.1,
            trend: 'Declining',
            assessmentDate: '2022-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 7,
            assessmentYear: 2023,
            annualRecharge: 39.2,
            extractableResources: 35.28,
            totalExtraction: 148.3,
            stageOfExtraction: 'Over-Exploited',
            extractionRatio: 420.5,
            trend: 'Declining',
            assessmentDate: '2023-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },

        // Rajasthan Over-Exploited District (Region ID 8)
        {
            regionId: 8,
            assessmentYear: 2019,
            annualRecharge: 35.8,
            extractableResources: 32.22,
            totalExtraction: 118.5,
            stageOfExtraction: 'Over-Exploited',
            extractionRatio: 367.8,
            trend: 'Declining',
            assessmentDate: '2019-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 8,
            assessmentYear: 2020,
            annualRecharge: 28.3,
            extractableResources: 25.47,
            totalExtraction: 125.9,
            stageOfExtraction: 'Over-Exploited',
            extractionRatio: 494.3,
            trend: 'Declining',
            assessmentDate: '2020-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 8,
            assessmentYear: 2021,
            annualRecharge: 42.1,
            extractableResources: 37.89,
            totalExtraction: 128.7,
            stageOfExtraction: 'Over-Exploited',
            extractionRatio: 339.7,
            trend: 'Declining',
            assessmentDate: '2021-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 8,
            assessmentYear: 2022,
            annualRecharge: 31.7,
            extractableResources: 28.53,
            totalExtraction: 135.2,
            stageOfExtraction: 'Over-Exploited',
            extractionRatio: 474.0,
            trend: 'Declining',
            assessmentDate: '2022-06-15',
            dataSource: 'CGWB',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            regionId: 8,
            assessmentYear: 2023,
            annualRecharge: 26.9,
            extractableResources: 24.21,
            totalExtraction: 141.8,
            stageOfExtraction: 'Over-Exploited',
            extractionRatio: 585.8,
            trend: 'Declining',
            assessmentDate: '2023-06-15',
            dataSource: 'State GW Board',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }
    ];

    await db.insert(groundwaterAssessments).values(sampleAssessments);
    
    console.log('✅ Groundwater assessments seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});