import { db } from '@/db';
import { regions } from '@/db/schema';

async function main() {
    const sampleRegions = [
        // States
        {
            id: 1,
            name: 'Karnataka',
            type: 'state',
            parentId: null,
            code: 'KA',
            latitude: 15.3173,
            longitude: 75.7139,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 5,
            name: 'Maharashtra',
            type: 'state',
            parentId: null,
            code: 'MH',
            latitude: 19.7515,
            longitude: 75.7139,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 9,
            name: 'Rajasthan',
            type: 'state',
            parentId: null,
            code: 'RJ',
            latitude: 27.0238,
            longitude: 74.2179,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 13,
            name: 'Punjab',
            type: 'state',
            parentId: null,
            code: 'PB',
            latitude: 31.1471,
            longitude: 75.3412,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 17,
            name: 'Tamil Nadu',
            type: 'state',
            parentId: null,
            code: 'TN',
            latitude: 11.1271,
            longitude: 78.6569,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 21,
            name: 'Uttar Pradesh',
            type: 'state',
            parentId: null,
            code: 'UP',
            latitude: 26.8467,
            longitude: 80.9462,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Karnataka Districts
        {
            id: 2,
            name: 'Bangalore Urban',
            type: 'district',
            parentId: 1,
            code: 'KA-BLR',
            latitude: 12.9716,
            longitude: 77.5946,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 3,
            name: 'Mysore',
            type: 'district',
            parentId: 1,
            code: 'KA-MYS',
            latitude: 12.2958,
            longitude: 76.6394,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 4,
            name: 'Bellary',
            type: 'district',
            parentId: 1,
            code: 'KA-BLY',
            latitude: 15.1394,
            longitude: 76.9214,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Maharashtra Districts
        {
            id: 6,
            name: 'Mumbai',
            type: 'district',
            parentId: 5,
            code: 'MH-MUM',
            latitude: 19.0760,
            longitude: 72.8777,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 7,
            name: 'Pune',
            type: 'district',
            parentId: 5,
            code: 'MH-PUN',
            latitude: 18.5204,
            longitude: 73.8567,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 8,
            name: 'Nashik',
            type: 'district',
            parentId: 5,
            code: 'MH-NSK',
            latitude: 19.9975,
            longitude: 73.7898,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Rajasthan Districts
        {
            id: 10,
            name: 'Jaipur',
            type: 'district',
            parentId: 9,
            code: 'RJ-JPR',
            latitude: 26.9124,
            longitude: 75.7873,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 11,
            name: 'Jodhpur',
            type: 'district',
            parentId: 9,
            code: 'RJ-JDH',
            latitude: 26.2389,
            longitude: 73.0243,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 12,
            name: 'Bikaner',
            type: 'district',
            parentId: 9,
            code: 'RJ-BKN',
            latitude: 28.0229,
            longitude: 73.3119,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Punjab Districts
        {
            id: 14,
            name: 'Ludhiana',
            type: 'district',
            parentId: 13,
            code: 'PB-LDH',
            latitude: 30.9010,
            longitude: 75.8573,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 15,
            name: 'Amritsar',
            type: 'district',
            parentId: 13,
            code: 'PB-ASR',
            latitude: 31.6340,
            longitude: 74.8723,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 16,
            name: 'Patiala',
            type: 'district',
            parentId: 13,
            code: 'PB-PTA',
            latitude: 30.3398,
            longitude: 76.3869,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Tamil Nadu Districts
        {
            id: 18,
            name: 'Chennai',
            type: 'district',
            parentId: 17,
            code: 'TN-CHN',
            latitude: 13.0827,
            longitude: 80.2707,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 19,
            name: 'Coimbatore',
            type: 'district',
            parentId: 17,
            code: 'TN-CBE',
            latitude: 11.0168,
            longitude: 76.9558,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 20,
            name: 'Salem',
            type: 'district',
            parentId: 17,
            code: 'TN-SLM',
            latitude: 11.6643,
            longitude: 78.1460,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Uttar Pradesh Districts
        {
            id: 22,
            name: 'Lucknow',
            type: 'district',
            parentId: 21,
            code: 'UP-LKO',
            latitude: 26.8467,
            longitude: 80.9462,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 23,
            name: 'Kanpur',
            type: 'district',
            parentId: 21,
            code: 'UP-KNP',
            latitude: 26.4499,
            longitude: 80.3319,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 24,
            name: 'Varanasi',
            type: 'district',
            parentId: 21,
            code: 'UP-VNS',
            latitude: 25.3176,
            longitude: 82.9739,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Blocks for Bangalore Urban
        {
            id: 25,
            name: 'Yelahanka',
            type: 'block',
            parentId: 2,
            code: 'KA-BLR-YLK',
            latitude: 13.1007,
            longitude: 77.5963,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 26,
            name: 'Domlur',
            type: 'block',
            parentId: 2,
            code: 'KA-BLR-DML',
            latitude: 12.9606,
            longitude: 77.6387,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        // Blocks for Mumbai
        {
            id: 27,
            name: 'Andheri',
            type: 'block',
            parentId: 6,
            code: 'MH-MUM-AND',
            latitude: 19.1136,
            longitude: 72.8697,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        },
        {
            id: 28,
            name: 'Bandra',
            type: 'block',
            parentId: 6,
            code: 'MH-MUM-BND',
            latitude: 19.0596,
            longitude: 72.8295,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
        }
    ];

    await db.insert(regions).values(sampleRegions);
    
    console.log('✅ Regions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});